// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agenda.sql

package db

import (
	"context"
)

const countAgendaItems = `-- name: CountAgendaItems :one
SELECT count(*) FROM agenda_items
`

func (q *Queries) CountAgendaItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgendaItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}
