// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AgendaItem struct {
	ID          int64
	Source      string
	SourceID    string
	Kind        string
	CourseID    sql.NullInt64
	Title       string
	StartsAt    int64
	EndsAt      sql.NullInt64
	AllDay      int64
	SourceUrl   sql.NullString
	Status      string
	ContentHash string
	FirstSeenAt int64
	UpdatedAt   int64
}

type Course struct {
	ID        int64
	Code      string
	Name      string
	CreatedAt int64
}

type SyncState struct {
	Source        string
	Etag          sql.NullString
	LastModified  sql.NullString
	BodyHash      sql.NullString
	LastSuccessAt sql.NullInt64
	LastError     sql.NullString
}
