// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
	"database/sql"
)

const getSyncState = `-- name: GetSyncState :one
SELECT source, cursor, last_attempt_at, last_success_at, last_error, consecutive_failures FROM sync_state WHERE source = ?
`

func (q *Queries) GetSyncState(ctx context.Context, source string) (SyncState, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, source)
	var i SyncState
	err := row.Scan(
		&i.Source,
		&i.Cursor,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
		&i.LastError,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const saveSyncError = `-- name: SaveSyncError :exec
INSERT INTO sync_state (source, last_attempt_at, last_error, consecutive_failures)
VALUES (?, ?, ?, 1)
ON CONFLICT (source) DO UPDATE SET
    last_attempt_at      = excluded.last_attempt_at,
    last_error           = excluded.last_error,
    consecutive_failures = consecutive_failures + 1
`

type SaveSyncErrorParams struct {
	Source        string
	LastAttemptAt sql.NullInt64
	LastError     sql.NullString
}

func (q *Queries) SaveSyncError(ctx context.Context, arg SaveSyncErrorParams) error {
	_, err := q.db.ExecContext(ctx, saveSyncError, arg.Source, arg.LastAttemptAt, arg.LastError)
	return err
}

const saveSyncSuccess = `-- name: SaveSyncSuccess :exec
INSERT INTO sync_state (source, cursor, last_attempt_at, last_success_at, last_error, consecutive_failures)
VALUES (?, ?, ?, ?, NULL, 0)
ON CONFLICT (source) DO UPDATE SET
    cursor               = excluded.cursor,
    last_attempt_at      = excluded.last_attempt_at,
    last_success_at      = excluded.last_success_at,
    last_error           = NULL,
    consecutive_failures = 0
`

type SaveSyncSuccessParams struct {
	Source        string
	Cursor        sql.NullString
	LastAttemptAt sql.NullInt64
	LastSuccessAt sql.NullInt64
}

func (q *Queries) SaveSyncSuccess(ctx context.Context, arg SaveSyncSuccessParams) error {
	_, err := q.db.ExecContext(ctx, saveSyncSuccess,
		arg.Source,
		arg.Cursor,
		arg.LastAttemptAt,
		arg.LastSuccessAt,
	)
	return err
}

const upsertCourse = `-- name: UpsertCourse :one
INSERT INTO courses (code, name, created_at)
VALUES (?, ?, ?)
ON CONFLICT (code) DO UPDATE SET code = excluded.code
RETURNING id
`

type UpsertCourseParams struct {
	Code      string
	Name      string
	CreatedAt int64
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCourse, arg.Code, arg.Name, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}
