// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
	"database/sql"
)

const getSyncState = `-- name: GetSyncState :one
SELECT source, etag, last_modified, body_hash, last_success_at, last_error FROM sync_state WHERE source = ?
`

func (q *Queries) GetSyncState(ctx context.Context, source string) (SyncState, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, source)
	var i SyncState
	err := row.Scan(
		&i.Source,
		&i.Etag,
		&i.LastModified,
		&i.BodyHash,
		&i.LastSuccessAt,
		&i.LastError,
	)
	return i, err
}

const saveSyncError = `-- name: SaveSyncError :exec
INSERT INTO sync_state (source, last_error)
VALUES (?, ?)
ON CONFLICT (source) DO UPDATE SET last_error = excluded.last_error
`

type SaveSyncErrorParams struct {
	Source    string
	LastError sql.NullString
}

func (q *Queries) SaveSyncError(ctx context.Context, arg SaveSyncErrorParams) error {
	_, err := q.db.ExecContext(ctx, saveSyncError, arg.Source, arg.LastError)
	return err
}

const saveSyncSuccess = `-- name: SaveSyncSuccess :exec
INSERT INTO sync_state (source, etag, last_modified, body_hash, last_success_at, last_error)
VALUES (?, ?, ?, ?, ?, NULL)
ON CONFLICT (source) DO UPDATE SET
    etag            = excluded.etag,
    last_modified   = excluded.last_modified,
    body_hash       = excluded.body_hash,
    last_success_at = excluded.last_success_at,
    last_error      = NULL
`

type SaveSyncSuccessParams struct {
	Source        string
	Etag          sql.NullString
	LastModified  sql.NullString
	BodyHash      sql.NullString
	LastSuccessAt sql.NullInt64
}

func (q *Queries) SaveSyncSuccess(ctx context.Context, arg SaveSyncSuccessParams) error {
	_, err := q.db.ExecContext(ctx, saveSyncSuccess,
		arg.Source,
		arg.Etag,
		arg.LastModified,
		arg.BodyHash,
		arg.LastSuccessAt,
	)
	return err
}

const upsertCourse = `-- name: UpsertCourse :one
INSERT INTO courses (code, name, created_at)
VALUES (?, ?, ?)
ON CONFLICT (code) DO UPDATE SET code = excluded.code
RETURNING id
`

type UpsertCourseParams struct {
	Code      string
	Name      string
	CreatedAt int64
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCourse, arg.Code, arg.Name, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}
